### ISSUE TITLE
Add .desktop in this project or upstream project

### ISSUE THREAD

**Issue by farribeiro** [flathub/br.app.pw3270.terminal#1]
I noticed what the app haven't a desktop file in the gnome

To appreciate
Best regards
Fábio

**Comment by PerryWerneck** [comment]
I'm not very skylled in flathub but it doesnt follow the standard paths? The makefile installs the .desktop and application icons in the standard paths after ${DESTDIR}. 

Does flathub requires this files in another path?
 
As I understood the build-dir/files is the 'root' of flathub image; am I wrong? 

Checking the build-dir the .desktop is in the standard path at build-dir/files/share/applications/br.app.pw3270.terminal.desktop and the application icons are in the standard paths at build-dir/files/share/icons/hicolor/scalable/apps/br.app.pw3270.terminal.svg and build-dir/files/share/icons/hicolor/symbolic/apps/br.app.pw3270.terminal-symbolic.svg

**Comment by farribeiro** [comment]
I can assist you in putting this missing file to flathub/gnome.

The icons preferably only one size (256x256), you have to install (if your preference is to use your own yaml for that use the command `install -Dm644 ...` ) ... in the absolute path `/app/share/icons/hicolor /256x256/br.app.pw3270.terminal.png` (remember is the id) you can also put the svg in hicolor/scalable

the desktop file is to be placed in the absolute path `/app/share/applications/br.app.pw3270.terminal.desktop` with a similar content:

```
[Desktop Entry]
Name=KVIrc
GenericName=IRC Client
GenericName[de]=IRC Client
GenericName[pl]=Klient IRC
GenericName[pt]=Cliente IRC
GenericName[tr]=IRC İstemcisi
GenericName[es]=Cliente de IRC
Comment=Connect to Internet Relay Chat
Comment[de]=Internet Relay Chat betreten.
Comment[pl]=Połącz się z Internet Relay Chat (IRC)
Comment[pt]=Conectar ao IRC (Internet Relay Chat)
Comment[tr]=IRC'e bağlanın
Comment[es]=Conectar al chat IRC
Exec=kvirc -m %u
Icon=net.kvirc.KVIrc
Type=Application
MimeType=application/x-kva;application/x-kvt;
Categories=Qt;Network;IRCClient;
```
or... 

```
[Desktop Entry]
Version=1.0
Name=Gummi
GenericName=LaTeX Editor
Comment=Simple LaTeX Editor
Comment[de]=Einfacher LaTeX-Editor
Exec=gummi %F
Icon=app.gummi.gummi
Terminal=false
Type=Application
Categories=Office;
Keywords=latex;editor;
StartupNotify=true
MimeType=text/x-tex;
```

if you need a rework in the icons, desktop and/or appdata, you can use `rename-*` entry in yaml look in https://docs.flatpak.org/en/latest/manifests.html

BTW... or use autotools in upstream to install the files already with the app

I hope this info is useful
Best regards,
Fábio
